### ISSUE TITLE
Nice project, keep on working! What is the usage of AesFlushingCipherMod?

### ISSUE THREAD

**Issue by NanyangTaiji** [Rajshah2320/EncryptedExoPlayer#2]

**Comment by Rajshah2320** [comment]
It is used by exoplayer to decrypt the file on the fly.

**Comment by NanyangTaiji** [comment]
However, it is not used in your app!

**Comment by Rajshah2320** [comment]
Yeah my bad, i was using that class earlier as needed some customisations. It is not required in this app.
